version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:8
    ports:
      - "4000:3306"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=jch
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF_8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - ./mysql:/var/lib/mysql
      - ./entrypoint:/docker-entrypoint-initdb.d/
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  api:
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build: ./api
    ports:
      - 81:3000
